import pygame as pg
import time

#Game setup
font = pg.font.Font(None, 36)

#Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
screen = pg.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

#Player settings
PLAYER_START_POS_X = SCREEN_WIDTH//2
PLAYER_START_POS_Y = SCREEN_HEIGHT//2
PLAYER_SPEED = 8
PLAYER_RADIUS = 20

#Bullet setting
BULLET_SPEED = 6
BULLETS_SHOOTING_INTERVAL = 0.05
BULLETS_MAG_SIZE = 15
BULLETS_RELOAD_TIME = 2
BULLET_RADIUS = 4

#Daboss
BOSS_RADIUS = 100
BOSS_START_POS_X = SCREEN_WIDTH//2
BOSS_START_POS_Y = SCREEN_HEIGHT
BOSS_SPEED = 4
BOSS_BULLET_YES = [0, 1]
