#Game setup
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

#Player settings
PLAYER_START_POS_X = SCREEN_WIDTH//2
PLAYER_START_POS_Y = SCREEN_HEIGHT//2
PLAYER_SPEED = 8

#Bullet setting
BULLET_SPEED = 6
BULLETS_SHOOTING_INTERVAL = 0.05
BULLETS_MAG_SIZE = 15
BULLETS_RELOAD_TIME = 2